### ISSUE TITLE
Look into using Lerna for package management

### ISSUE THREAD

**Issue by amireh** [megadoc/megadoc#98]
https://github.com/lerna/lerna is what is used by babel, it's _probably_ :trollface: better than the home-grown bin/ bash scripts here.

**Comment by landonwilkins** [comment]
simple as `lerna init` [x]
killer dragon [x]
such win

then `lerna bootstrap` instead of `bin/setup` ?

**Comment by landonwilkins** [comment]
`lerna init` isn't a command anymore, just `lerna bootstrap` looks like

```
➜  megadoc git:(lerna) ✗ lerna bootstrap

Lerna bootstrap v1.1.2

Current version: 0.0.0
Version file location: /Users/lwilkins/sandbox/megadoc/VERSION
Packages location: /Users/lwilkins/sandbox/megadoc/packages

megadoc-plugin-react                               ╢██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░╟sh: ./bin/lint: No such file or directory

npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/lwilkins/.nvm/versions/node/v5.0.0/bin/node" "/Users/lwilkins/.nvm/versions/node/v5.0.0/bin/npm" "run" "lint"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! megadoc@5.0.1 lint: `./bin/lint && ./bin/lint-ui`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the megadoc@5.0.1 lint script './bin/lint && ./bin/lint-ui'.
npm ERR! This is most likely a problem with the megadoc package,
```

**Comment by landonwilkins** [comment]
ooo, `lerna init` is coming in 2.0
`npm install --global lerna@2.0.0-beta.13` ftw

**Comment by landonwilkins** [comment]
aww man, thought i could get rid of all the node_modules, then remove

```
    "lint": "./bin/lint && ./bin/lint-ui",
    "prepublish": "npm run lint && npm run build && npm run test",
```

then

```
lerna init
lerna bootstrap
NODE_PATH=$(pwd)/packages ./cli/megadoc --config ../meteor/megadoc.conf.js
```

but then i get

```
➜  megadoc git:(lerna) ✗ VERBOSE=1 NODE_PATH=$(pwd)/packages ./cli/megadoc --config ../meteor/megadoc.conf.js
module.js:339
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/lwilkins/sandbox/megadoc/cli/megadoc:3:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
```

so i had to run `bin/setup` to get it working again

**Comment by amireh** [comment]
Huh hmm

Maybe lerna isn't installing modules from the root `package.json`?

There is one modification I know we have to do for lerna compatibility which is to move stuff under `lib/` and `ui/` into `packages/megadoc-core` and move `cli/` into `packages/megadoc-cli` then we can make the base package `megadoc` depend on both `megadoc-core`, `megadoc-cli` so that people don't have to specify these manually, and have our plugins rely on `megadoc-core` instead of `megadoc`.

Does that make sense?
